// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3VyGaVEjoGmgfYcb2gkIdEGwU1IItJD0',
    appId: '1:400975108323:web:a3fdc0135ecf0bcfe18dd6',
    messagingSenderId: '400975108323',
    projectId: 'library-20c0c',
    authDomain: 'library-20c0c.firebaseapp.com',
    storageBucket: 'library-20c0c.appspot.com',
    measurementId: 'G-H5647SKCSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBooB7ca5f-Lshd-IJIIXkeYtyet_WC9M',
    appId: '1:400975108323:android:4200fc6b73e6a6dee18dd6',
    messagingSenderId: '400975108323',
    projectId: 'library-20c0c',
    storageBucket: 'library-20c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbUfHHkMq9BXJmbSpZwSIz880-DefFHw',
    appId: '1:400975108323:ios:75a6f2e060846736e18dd6',
    messagingSenderId: '400975108323',
    projectId: 'library-20c0c',
    storageBucket: 'library-20c0c.appspot.com',
    iosClientId: '400975108323-trvdcbin1asi1sf5dvsudlmjjpmdv8cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApbUfHHkMq9BXJmbSpZwSIz880-DefFHw',
    appId: '1:400975108323:ios:75a6f2e060846736e18dd6',
    messagingSenderId: '400975108323',
    projectId: 'library-20c0c',
    storageBucket: 'library-20c0c.appspot.com',
    iosClientId: '400975108323-trvdcbin1asi1sf5dvsudlmjjpmdv8cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment4',
  );
}
